# APPLICATION and PROFILE
spring.application.name=TinyVillageHub
spring.profiles.default=dev

# JWT SETTINGS (Will eventually move secret to an environment variable)
jwt.expiration=600000
jwt.refresh.expiration=604800000
jwt.secret=YVNCdEFES2N0b0p6Y2IzaWR0TjhrYml2M1J0TjhrYml2M1I0Yz)qs(234HyhOasd=
# SHARED LOGGING SETTINGS
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.segatto_builder.tinyvillagehub=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/tinyvillagehub.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB

# SCHEDULER SETTINGS
scheduler.token-cleanup.enable=true
scheduler.token-cleanup.interval=86400000

# Items Service Configuration
items-service.url=http://item-service:8080



